sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 64257019aA@
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQ93iKK8oMzuQrGoRz5
    access-key-secret: cDLr1POs2F853sydBrzhkMeiB3elay
    bucket-name: skytak
  redis:
    host: localhost
    port: 6379
    password: 64257019aA@
    database: 0
  wechat:
    appid: wx98795b4880a6232f
    secret: 8081c10307920ff21dac46a3e9316bb0
